recipe: default.v1
language: en

pipeline:
  - name: WhitespaceTokenizer

  - name: RegexFeaturizer
    use_word_boundaries: True

  - name: CountVectorsFeaturizer
    min_ngram: 1
    max_ngram: 3
    analyzer: "word"
    stop_words: "english"

  - name: CountVectorsFeaturizer
    min_ngram: 1
    max_ngram: 3
    analyzer: "char_wb"

  - name: DIETClassifier
    epochs: 150
    learning_rate: 0.002
    embedding_dimension: 60
    batch_size: [64, 128]
    constrain_similarities: True

  - name: EntitySynonymMapper

  - name: ResponseSelector
    epochs: 150
    learning_rate: 0.002
    embedding_dimension: 60
    batch_size: [64, 128]
    constrain_similarities: True

  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.2

  - name: SpacyNLP
    model: "en_core_web_md"
    case_sensitive: False

  - name: SpacyEntityExtractor
    dimensions: ["PERSON", "ORG", "GPE", "DATE"]

policies:
  - name: MemoizationPolicy

  - name: RulePolicy

  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 150

  - name: TEDPolicy
    max_history: 10
    epochs: 150
    batch_size: [32, 64]

assistant_id: 20241214-005454-flashed-guaranty
